### PR TITLE
Marked framework build schema as shared to support Carthage.

### PR DESCRIPTION
**Pull request by regexident**
See title.

### CODE REVIEW

**Comment by jwilling** [comment]
Sorry for the delay. Can you explain what this does? It seems to have added another schema that's a duplicate of the original one, with a 32-bit target. This project doesn't support 32-bit architectures, so that might not be a good idea. Also, it seems like the scheme isn't set up quite correctly, as it's trying to enable garbage collection on the testing libraries (which I plan to remove when I get the chance).

I'm sorry that I can't merge this right now, as I'm currently under some license restrictions at my current employer. Once I hopefully get that resolved I can help you get this in.

**Comment by regexident** [comment]
All I did was checking the "Shared" checkbox for the "JNWCollectionView" (framework) build target under "Manage Schemes" (as Carthage requires framework targets to be marked as such in order to be supported by Carthage). Looks like that's what Xcode does when marking a target as shared.

**Comment by jwilling** [comment]
Alright. I'll get back to you once I've been cleared for open source. Hopefully that'll happen soon, otherwise it might be a long time before I can get on this. Sorry. :cry:

**Comment by danielmartinprieto** [comment]
Hi, @regexident. I'm using your fork of this library trying to use it via Carthage. The framework has been built with Carthage and added to the project as embebed binary without any problem, but I can't get it working, when I import JNWCollectionView, Xcode gives me the "No such module 'JNWCollectionView'" error. Am I missing anything here?

Thanks for your help.

**Comment by jwilling** [comment]
Fixed in master. Thanks!

**Pull request closed without merging**
