### PR TITLE
Added modifierFlags parameter to mouseUp/Down delegate methods

### PR DESCRIPTION
**Pull request by kettch**
Adding support for modifier flags in delegate calls for mouseUp / mouseDown.

### CODE REVIEW

**Comment by jwilling** [comment]
I like this change. However, since I unfortunately don't have some sort of release notes for this library, I'm worried that changing the signature of this delete method could potentially be an issue for backwards compatibility. What are your thoughts on that?

**Comment by kettch** [comment]
I'll double-check that, but if I remember correctly, the end goal for this is to be able to handle complex selection cases from within those delegate calls. Namely, Cmd-clicks and Shift-clicks to build selections.

**Comment by jwilling** [comment]
Got it. What I'm worried about is if someone had previously implemented this delegate method, it would not not function due to the signature being different. Since the delegate method isn't required, Clang wouldn't even provide a warning for it. I'm curious if it's possible to use a deprecated attribute on methods in a protocol? I will investigate.

**Comment by jwilling** [comment]
It looks like the `__deprecated` attribute will provide a warning for implementing deprecated protocol methods. I think the best approach here is to add back the existing protocol methods but add the deprecated attribute to them. Something like this:


``` objc
/// Tells the delegate that the mouse is down inside of the item at the specified index path with specific modifier flags.
- (void)collectionView:(JNWCollectionView *)collectionView mouseDownInItemAtIndexPath:(NSIndexPath *)indexPath withModifierFlags:(NSEventModifierFlags)modFlags;

/// Tells the delegate that the mouse click originating from the item at the specified index path is now up with specific modifier flags.
///
/// The mouse up event can occur outside of the originating cell.
- (void)collectionView:(JNWCollectionView *)collectionView mouseUpInItemAtIndexPath:(NSIndexPath *)indexPath withModifierFlags:(NSEventModifierFlags)modFlags;

- (void)collectionView:(JNWCollectionView *)collectionView mouseDownInItemAtIndexPath:(NSIndexPath *)indexPath __deprecated_msg("Use collectionView:mouseDownInItemAtIndexPath:withModifierFlags: instead.");
- (void)collectionView:(JNWCollectionView *)collectionView mouseUpInItemAtIndexPath:(NSIndexPath *)indexPath __deprecated_msg("Use collectionView:mouseUpInItemAtIndexPath:withModifierFlags: instead.");
```

Think that'll work?

**Comment by kettch** [comment]
Sure, will try that first thing tomorrow and push it!

**Comment by kettch** [comment]
I'm closing this pull request, as this change has been changed further for drag and drop support, so I want to avoid conflicts and branches interacting together...

**Pull request closed without merging**
