### PR TITLE
Notify delegate when selection is removed from cells due to data reloading

### PR DESCRIPTION
**Pull request by plumbojumbo**

### CODE REVIEW

**Comment by jwilling** [comment]
Solid, thanks! :sparkles:

**Comment by crazymaik** [comment]
Hi,

Just ran into this issue. I wonder if self.selectedIndexes should be updated before `didDeselectItemAtIndexPath` is called? This would be the same contract as `deselectItemAtIndexPath` where the array is updated first.

In my app I do a check on the array if no more items are selected in the `didDeselectItemAtIndexPath`, but since the array is not up to date the wrong code path is chosen.

**Comment by jwilling** [comment]
@crazymaik Good call. I believe that behavior sounds reasonable. Would you be willing to open a pull request with that change? I'll be happy to merge it in.

**Comment by crazymaik** [comment]
Created a new PR.

**Pull request merged**
