### PR TITLE
Added JNWCollectionViewCell binding capabilities (#149)

### PR DESCRIPTION
**Pull request by Deadpikle**
It doesn't work _exactly_ the same as an NSTableView or NSCollectionView binding, but it isn't too hard to set up. I've added on to the demo in order to demonstrate how to set up a data binding. I kept both the NSObjectController and the objectValue properties so that users can set up the binding how they desire.

### CODE REVIEW

**Comment by Deadpikle** [comment]
@jwilling No worries! Life is busy for all of us. 

I think it should be OK? I've continued to use it in my work project with no issues, but it's possible I tweaked something without thinking about it. Give me the weekend to double check it, if you don't mind. I want to make sure I haven't done anything kooky or fixed any other bugs in the mean time in my fork of the repo that has some unstable features (Deadpikle:develop). I think I'll have some time late this afternoon or Sunday evening to look at everything. I'll comment again with another comment highlight when I've got everything sorted.

**Comment by jwilling** [comment]
Sounds great! Thank you.

**Comment by Deadpikle** [comment]
@jwilling Should be good to go! Seems to be working fine still. I went ahead and updated to Xcode 8 as well as fixed some deprecation warnings.

**Comment by jwilling** [comment]
You're the best. Thanks! ⭐️

**Pull request merged**
