### PR TITLE
implements NSResponder scrolling methods

### PR DESCRIPTION
**Pull request by spilliams**

### CODE REVIEW

**Comment by jwilling** [comment]
Thanks for this pull request! :heart: Couldn't get to this earlier as I was on vacation.

I feel like possibly a better way to accomplish this would be to scroll to the first and last index paths, rather than scrolling to the top and the bottom of the scroll view. This would help alleviate the problem you mentioned in a comment, which is that for non-linear layouts we don't know where the top and the bottom are. What do you think?

**Comment by spilliams** [comment]
I think the best we could do would be to specify "beginning" and "end" rects with a call to the layout. Only the layout knows where it begins and ends. I recommend putting methods `-(CGRect)rectForBeginning` and `-(CGRect)rectForEnd` in JNWCollectionViewLayout (to be implemented by subclasses).

Just using index paths won't completely solve the problem, because it's possible the last index path is not at the end of the document. Consider my staggered grid layout. Since the cells are placed in the shortest column available (regardless of the new cell's height), it's possible to end up in a situation where the last index path is still above the bottom of the layout.
image

I'll add this as an issue to my fork, but I'm not sure when I'll get around to it. Since the last time I worked on this I've spun up a few new projects.

**Comment by jwilling** [comment]
Right on, I didn't consider that case. For now this is probably our best bet.

**Comment by jwilling** [comment]
:palm_tree:

**Pull request merged**
