### PR TITLE
Drag n drop+hovering

### PR DESCRIPTION
**Pull request by kettch**
Mixes previous pull requests (adding info to mouseDown/mouseUp, and hovering support), and adds drag and drop support as well.
Drag and drop required adding the event to some delegate calls, so this negated the previous pull request for adding modifiers to some delegates, and I felt it was better to put them together to have them go in one pass and avoid problems. Sorry about that!

### CODE REVIEW

**Comment by jwilling** [comment]
It might take me a little bit longer to get to this. I've been out of town so I haven't been able to look at it yet.

**Comment by kettch** [comment]
No worries. I just saw that there had been some work on drag'n'drop already, so just let me know if splitting back hovering in its own separate branch might be easier for you. Seemed a good idea at the time, but these are 2 very different things still...

**Comment by jwilling** [comment]
This looks solid! I'm a little bit concerned however about the fact that there might be some overhead associated with the machinery implemented here. I'll comment on two areas where we might be able to mitigate some performance impact.

On a side note, I'm curious how adding tracking areas will impact performance. I have not done any benchmarking for them, so I don't know their overhead.

**Comment by kettch** [comment]
I have another thing pending on the drag'n'drop, but I was a bit reluctant to push it on top of this branch, as this one is already a mix of two different things. The branch is ready, so this can wait a bit.

Regarding performance of the tracking areas, we could go around that to mitigate for cases where you don't want the hovering but just adding an enable flag for it. And for the others, you don't have many choices for the hovering anyway. What do you think?

**Comment by jwilling** [comment]
Sorry for not looking at this again for a while, I've been kept busy with a lot of things. I think this looks fine to merge, so if you want to make those changes in a separate branch that should be fine.

I'm a little ambivalent about the tracking areas. I there is definitely some overhead, but I don't think it's worth the extra complication to selectively enable the tracking areas.

**Pull request merged**
